# Generated by Django 5.2 on 2025-05-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="log_file",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="out_dir",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("rnaseq", "RNA-seq"),
                    ("wgs", "Whole Genome Sequencing"),
                    ("wes", "Whole Exome Sequencing"),
                    ("methylation", "Methylation"),
                ],
                default="rnaseq",
                max_length=20,
            ),
        ),
    ]
