services:
  django:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: visualization_workbench
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    ports:
      - "8001:8000"
    volumes:
      - ./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
